# integration tests for vitest ecosystem - single run of selected testsuite
name: vitest-ecosystem-ci-selected

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

on:
  workflow_dispatch:
    inputs:
      refType:
        description: "type of vitest ref to use"
        required: true
        type: choice
        options:
          - branch
          - tag
          - commit
          - release
        default: "branch"
      ref:
        description: "vitest ref to use"
        required: true
        type: string
        default: "main"
      repo:
        description: "vitest repository to use"
        required: true
        type: string
        default: "vitest-dev/vitest"
      suite:
        description: "testsuite to run"
        required: true
        type: choice
        options:
          - aria-live-capture
          - nuxt-test-utils
          - chromatic
          - vitest-vscode
          - vitest-sonar-reporter
          - vitest-browser-examples
          - vitest-coverage-large-browser
          - vitest-coverage-large-node
          - vitest-reporters-large
          - vitest-benchmark-large
          - vitest-pool-example
          - vitest-pool-workers
          - vitest-in-webcontainer

jobs:
  execute-selected-suite:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
        id: setup-node
        continue-on-error: true

      - run: corepack enable

      - run: pnpm --version

      - run: pnpm i --frozen-lockfile

      - run: >-
          pnpm tsx ecosystem-ci.ts
          --${{ inputs.refType }} ${{ inputs.ref }}
          --repo ${{ inputs.repo }}
          ${{ inputs.suite }}
        id: ecosystem-ci-run

      - if: always()
        run: pnpm tsx discord-webhook.ts
        env:
          WORKFLOW_NAME: ci-selected
          REF_TYPE: ${{ inputs.refType }}
          REF: ${{ inputs.ref }}
          REPO: ${{ inputs.repo }}
          SUITE: ${{ inputs.suite }}
          STATUS: ${{ job.status }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
